Proper v12 typings
zajrik/discord.js-typings pull request #44
Opened 2017-08-23 22:19 UTC by iCrawl

2017-08-24 15:28 UTC, PgBiel requested changes

2017-08-24 15:28 UTC, PgBiel commented on index.d.ts
> +		public setExcplicitContentFilter(explicitContentFilter: number, reason?: string): Promise<Guild>;
"Excplicit" is not correct

2017-08-25 03:16 UTC, iCrawl commented on index.d.ts
> +		public setExcplicitContentFilter(explicitContentFilter: number, reason?: string): Promise<Guild>;
tfw

2017-08-26 00:32 UTC, PgBiel commented
should probably look the data store thing

2017-09-22 20:58 UTC, PgBiel commented
🤔

2017-09-28 01:35 UTC, kzay commented
There is some issue, like the users type in Client objects (now is UserStore)

2017-10-02 22:07 UTC, zajrik commented
Going to go ahead and merge this for now. Looks like we still need DataStore stuff but that's going to be generics I believe so I'll have to tackle it

2017-10-02 22:07 UTC, merged